spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jpashop
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: dkfktl92

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
 #       show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug



