spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jpashop
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: dkfktl92
  server:
    port: 8081
    context-path: /api
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    repositories:
      bootstrap-mode: default

logging:
  level:
    org.hibernate.SQL: debug



